services:
  bind9:
    build: 
      context: ./bind
      dockerfile: Dockerfile
    ports:
      - "1053:53/tcp"
      - "1053:53/udp"
    volumes:
      - ./bind/config:/etc/bind:rw
      - ./bind/zones:/var/lib/bind:rw
      - ./bind/cache:/var/cache/bind:rw
      - ./bind/run:/var/run/named:rw
    environment:
      - TZ=UTC
    restart: always
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    restart: always
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: dnsadmin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: dns_manager
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  dns_manager:
    build:
      context: ./dns_manager
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - bind9
      - nginx-proxy-manager
    volumes:
      - ./bind/zones:/zones
    environment:
      - DB_HOST=postgres
      - DB_USER=dnsadmin
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=dns_manager
      - NPM_API_URL=http://nginx-proxy-manager:81
      - NPM_EMAIL=${NPM_EMAIL}
      - NPM_PASSWORD=${NPM_PASSWORD}
volumes:
  postgres_data: