version: '3.8'

services:
  bind9:
    container_name: dns-server
    build: 
      context: ./bind
      dockerfile: Dockerfile
    ports:
      - "5300:53/tcp"  # Use alternative port
      - "5300:53/udp"  # Use alternative port
    volumes:
      - ./bind/config:/etc/bind
      - ./bind/zones:/var/lib/bind
      - ./bind/cache:/var/cache/bind
    restart: always

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: dnsadmin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: dns_manager
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  dns_manager:
    build:
      context: ./dns_manager
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - bind9
      - nginx-proxy-manager
    volumes:
      - ./bind/zones:/var/lib/bind
      - ./bind/config:/etc/bind
    environment:
      - DB_HOST=postgres
      - DB_USER=dnsadmin
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=dns_manager
      - NPM_API_URL=http://nginx-proxy-manager:81
      - NPM_EMAIL=${NPM_EMAIL}
      - NPM_PASSWORD=${NPM_PASSWORD}
      - ENV=production

volumes:
  postgres_data:

volumes:
  postgres_data:
