version: '3.8'

services:
  bind9:
    build: 
      context: ./bind
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:53:53/tcp"
      - "0.0.0.0:53:53/udp"
    volumes:
      - ./bind/config:/etc/bind:rw
      - bind9-cache:/var/cache/bind:rw
      - bind9-run:/var/run/named:rw
      - /records:/var/lib/bind:rw
    restart: always
    networks:
      dns_net:
        ipv4_address: 10.142.0.2
    privileged: true
    
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    restart: always
    networks:
      dns_net:
        ipv4_address: 10.142.0.3

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: dnsadmin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: dns_manager
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"  # Ensure this port mapping exists
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dnsadmin -d dns_manager"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      dns_net:
        ipv4_address: 10.142.0.4

  dns_manager:
    build:
      context: ./dns_manager
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      bind9:
        condition: service_started
      nginx-proxy-manager:
        condition: service_started
    volumes:
      - ./bind/zones:/zones
    environment:
      - DB_HOST=postgres  # Updated to service name
      - DB_USER=dnsadmin
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=dns_manager
      - NPM_API_URL=http://nginx-proxy-manager:81
      - NPM_EMAIL=${NPM_EMAIL}
      - NPM_PASSWORD=${NPM_PASSWORD}
    networks:
      dns_net:
        ipv4_address: 10.142.0.5

volumes:
  postgres_data:
  bind9-cache:
  bind9-run:

networks:
  dns_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.142.0.0/24